SUPABASE_URL = "https://vpljhpprbserfkhnslce.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbGpocHByYnNlcmZraG5zbGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4NzkwNDYsImV4cCI6MjA4MzQ1NTA0Nn0.j7p_RYfMbpFYVAleJg-W-M_fC7boZRLtXR7qirwYDps"
